add_library(lootinator
    include/lootinator/assertions.h
    include/lootinator/loot_table.h
    include/lootinator/lootinator.h
    include/lootinator/mc/minecraft.hpp
    include/lootinator/constraint/constraint.h
    include/lootinator/constraint/filter.h
    include/lootinator/template/helpers.h
    include/lootinator/template/kernel_template.h
    include/lootinator/template/template.h
    include/lootinator/utility/debug.h
    include/lootinator/utility/enum_bimap.hpp
    include/lootinator/utility/range.h
    include/lootinator/utility/mth.h
    include/lootinator/lsm/parser.hpp
    include/lootinator/lsm/instructions.hpp
    include/lootinator/lsm/constraints_to_lsm.hpp
    include/lootinator/lsm/cuda/lsm_to_cuda.hpp
    include/lootinator/template/template.h
    include/lootinator/template/template.h

    
    src/loot_table.cpp
    src/lootinator.cpp
    src/mc/minecraft.cpp
    src/constraint/constraint.cpp
    src/constraint/filter.cpp
    src/template/helpers.cpp
    src/template/kernel_template.cpp
    src/template/template.cpp
    src/lsm/instructions.cpp
    src/lsm/cuda/lsm_to_cuda.cpp
    src/lsm/parser.cpp
    src/lsm/constraints_to_lsm.cpp
    src/utility/debug.cpp
)

target_include_directories(lootinator PUBLIC include)

set(TEST_FILES
    tests/constraint_test.cpp
    tests/constraint_json_test.cpp
    tests/filter_test.cpp
)

# TODO: compiler flags, (-O3, warnings, etc)

# Create test driver and test source list
create_test_sourcelist(TEST_SOURCELIST CommonCxxTests.cxx ${TEST_FILES})

# Build test executable with the generated test driver
add_executable(test_driver ${TEST_SOURCELIST})
target_link_libraries(test_driver PRIVATE lootinator)

add_subdirectory(${CMAKE_SOURCE_DIR}/external/json ${CMAKE_BINARY_DIR}/json)
target_include_directories(lootinator PUBLIC ${CMAKE_SOURCE_DIR}/external/json/single_include/)
target_link_libraries(lootinator PRIVATE nlohmann_json::nlohmann_json)

foreach(test_file ${TEST_FILES})
    get_filename_component(test_name ${test_file} NAME_WE)
    add_test(NAME ${test_name} COMMAND test_driver tests/${test_name})
endforeach()
