name: lootinator-release-builds

on: [push]

jobs:
  linux:
    name: build/release/linux
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: |
        sudo apt update
        sudo apt install build-essentials

    - name: build
        mkdir build && cd build && cmake ..
        make -B -j8

    - uses: actions/upload-artifact@v4
      with:
        name: lootinator-cli-linux
        path: ./${{ github.event.repository.name }}/build/cli/lootinator-cli


